# Generated by Django 6.1.1 on 2026-10-05 14:54

import apps.domains.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0005_region_hierarchy'),
        ('facilities', '0004_facility_sort_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='region',
            field=models.ForeignKey(default=apps.domains.models.get_default_region_id, on_delete=django.db.models.deletion.PROTECT, related_name='facilities', to='domains.region'),
        ),
    ]
