# Generated by Django 6.0.6 on 2026-07-03 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('facilities', '0002_facility_timezone_color_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='physician',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='physician',
            name='clinician_type',
            field=models.CharField(choices=[('physician', 'Physician'), ('pa', 'PA'), ('np', 'NP')], default='physician', max_length=20),
        ),
        migrations.AddField(
            model_name='physician',
            name='display_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='physician',
            name='fte',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='physician',
            name='primary_facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_physicians', to='facilities.facility'),
        ),
    ]
