# Generated by Django 6.0.6 on 2026-07-11 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0016_manual_assignment_locks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
